djangoDemo/demo_settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("medical.urls")),
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
]

handler403 = "medical.views.custom_error_403"
handler404 = "medical.views.custom_error_404"

djangoDemo/medical/urls.py
# chat/urls.py
from django.urls import path

from . import views
from .views import PatientMedicalData, PatientData, NewPatient, PatientDetails

app_name = 'medical'

urlpatterns = [
    path("", views.index, name="index"),
    # path("rooms/<str:room_name>/", views.room, name="room"),
    path("patients/", views.patients, name="patients"),
    path("new_patient/", NewPatient.as_view(), name="new_patient"),
    path("patients/<int:pk>/", PatientDetails.as_view(), name="patient"),
    path("patients/<int:pk>/update_diagnose/", PatientMedicalData.as_view(), name="update_patient_diagnose"),
    path("patients/<int:pk>/update_patient_data/", PatientData.as_view(), name="update_patient"),
    path("patients/<int:pk>/blood_pressure/", views.blood_pressure, name="blood_pressure"),
    path("patients/<int:pk>/pulse/", views.pulse, name="pulse"),
    path("patients/<int:pk>/vital_status/", views.vital_status, name="vital_status"),
]

djangoDemo/medical/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import model_to_dict

from medical.model_manager import PatientManager



class Patient(models.Model):
    """
    Model for the Patientrecord
    """
    name = models.CharField(max_length=200)
    icd11_code = models.CharField(max_length=64, blank=True, default='')
    diagnosis_text = models.TextField(max_length=4096)
    attending_doctor = models.CharField(max_length=64,blank=True,default='')
    room_number = models.IntegerField()
    is_related_to_staff = models.BooleanField(default=False)

    objects_patients = PatientManager()

    def __str__(self):
        """String for representing the Patient-Model object."""
        return model_to_dict(self)

djangoDemo/medical/forms.py
from django import forms


class UpdatePatientData(forms.Form):
    attending_doctor = forms.CharField(label='attending doctor', max_length=50, required=False)
    room_number = forms.IntegerField(label='new room number', min_value=1, max_value=99, required=False)


class UpdatePatientDiagnose(forms.Form):
    diagnose = forms.CharField(label='new diagnose', max_length=1000, required=False)
    icd11 = forms.CharField(label='new icd', max_length=100, required=False)


class NewPatientForm(forms.Form):
    name = forms.CharField(label='name', max_length=50)
    attending_doctor = forms.CharField(label='attending doctor', max_length=50, required=False)
    room_number = forms.IntegerField(label='room number', min_value=1, max_value=99)
    diagnosis_text = forms.CharField(label='diagnose', max_length=1000)
    icd11_code = forms.CharField(label='icd', max_length=100, required=False)

djangoDemo/medical/views.py
# chat/views.py
from asgiref.sync import sync_to_async
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View
from medical.forms import UpdatePatientData, UpdatePatientDiagnose, NewPatientForm
from medical.models import Patient
from sapl_base.decorators import pre_enforce


async def index(request):
    """
    Maps to the endpoint "/" and renders a page with information about this Demo and a Button,
    where a User can log in. When a User is already logged in, he is redirected to the patients page.
    """
    user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
    if user_is_anonym:
        return render(request, "medical/home.html")
    return redirect("medical:patients")

@pre_enforce(action = "request_websocket")
async def vital_status(request, pk: int):
    user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
    if user_is_anonym:
        return redirect('medical:index')
    patient = await Patient.objects_patients.find_patient_by_pk(pk)
    if patient is None:
        return render(request, "medical/404.html")
    return render(request, "medical/patients/vital_status.html",{"patient": patient})

@pre_enforce(action = "request_websocket")
async def blood_pressure(request, pk: int):
    user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
    if user_is_anonym:
        return redirect('medical:index')
    patient = await Patient.objects_patients.find_patient_by_pk(pk)
    if patient is None:
        return render(request, "medical/404.html")
    return render(request, "medical/patients/blood_pressure.html",{"patient": patient})

@pre_enforce(action = "request_websocket")
async def pulse(request, pk: int):
    user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
    if user_is_anonym:
        return redirect('medical:index')
    patient = await Patient.objects_patients.find_patient_by_pk(pk)
    if patient is None:
        return render(request, "medical/404.html")
    return render(request, "medical/patients/pulse.html",{"patient": patient})



@pre_enforce
async def patients(request):
    """
    This function renders the view for the patient-list and maps to the endpoint "patients/"
    This Page is pre_enforced with SAPL and can only be accessed with a GET request from an authenticated User.
    Other request methods are denied

    The Policy which can apply for this Page is
    "Staff can see Patientlist" in the file views.sapl in the policies folder

    :param request: request for the view
    """
    user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
    if user_is_anonym:
        return redirect('medical:index')
    all_patients = await Patient.objects_patients.auth_user_view_all_patients()

    return render(request, "medical/patients/patient_list.html", {"patients": all_patients})


class PatientDetails(View):
    """
    Class based View to handle GET and POST Request for the URL "patients/<int:pk>/" which shows details of a patient.

    GET and POST requests are separately pre_enforced with SAPL.
    """

    @pre_enforce
    async def get(self, request, pk: int):
        """
        This method renders the view for a patient-record and is called by GET requests to the URL "patients/<int:pk>/"

        This Method is pre_enforced with SAPL and the Policies which can apply for this request are
        "Staff can see Patientlist" in the file views.sapl in the policies folder

        :param request: request for the view
        :param pk: id of the patient, which data shall be retrieved from the database.
        """
        user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
        if user_is_anonym:
            return redirect('medical:index')
        patient = await Patient.objects_patients.find_patient_by_pk(pk)
        if patient is None:
            return render(request, "medical/404.html")
        return render(request, "medical/patients/detailview.html",
                      {"patient": patient})

    @pre_enforce
    async def post(self, request, pk):
        """
        POST Request to this endpoint will attempt to delete the patient with the given id from the database.

        Only a User of the Group "Doctor" is allowed to send a POST request to this endpoint.
        The Policy which can apply for this request is "only Doctor can delete patients"
        in the file views.sapl in the policies folder

        @param request: Request which was made to the Server
        @param pk: id of the patient
        @return: redirects the client to the patients page
        """
        await Patient.objects_patients.delete_patient(pk)
        return redirect("medical:patients")


class NewPatient(View):
    """
    Class based View to add a new patient to the database

    GET and POST requests are both pre_enforced with SAPL
    """

    @pre_enforce
    async def get(self, request):
        """
        Function is called when a GET request is sent to the endpoint "new_patient/" it renders a view of a form which
        adds a new patient.

        This page can only be seen by Users of the Group "Nurse". The policy which is applied for requests to this endpoint is
        "Nurse and interns are allowed to see the view to add new Patients" in the file views.sapl in the policies folder

        @param request: Request which was made to the Server
        """
        user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
        if user_is_anonym:
            return redirect('medical:index')
        form = NewPatientForm()
        return render(request, "medical/patients/new_patient.html", {'form': form})

    @pre_enforce
    async def post(self, request):
        """
        Function is called, when a POST request is sent to the endpoint "new_patient/". It attempts to add a
        new patient to the database with the arguments provided

        Patients can only be added by Nurses. The Policy which is applied for POST requests to this endpoint is
        "Only Nurse can add new patients" in the file views.sapl in the policies folder.
        Although Interns are allowed to see the Page, they are not allowed to add
        new patients.

        @param request: Request which was made to the Server

        """
        user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
        if user_is_anonym:
            return redirect('medical:index')
        form = NewPatientForm(request.POST)

        if form.is_valid():
            patient = Patient(**form.cleaned_data)
            await sync_to_async(lambda: patient.save())()
            return redirect('medical:patient', patient.pk)

        messages.error(self.request, 'Form is invalid')
        return HttpResponseRedirect(self.request.path_info)


class PatientMedicalData(View):
    """
    Class based View to see and modify the medical data of a patient

    GET and POST requests are both pre_enforced with SAPL
    """

    @pre_enforce
    async def get(self, request, pk):
        """
        This method is called when a GET request is made to the endpoint "patients/<int:pk>/update_diagnose/"
        A page is rendered, which shows the medical data of the patient with the given pk.

        Only Users of the group "Doctor" are allowed to make a request to this endpoint. The policy which is applied to
        GET requests to this endpoint is policy "Only Doctor can update patients diagnose"
        @param request: Request, which was made to the Server
        @param pk: id of the patient, whose medical data will be displayed
        """
        user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
        if user_is_anonym:
            return redirect('medical:index')
        form = UpdatePatientDiagnose()
        patient = await Patient.objects_patients.find_patient_by_pk(pk)
        if patient is None:
            return render(request, "medical/404.html")
        return render(request, "medical/patients/update_diagnose.html", {'form': form, 'patient': patient})

    @pre_enforce
    async def post(self, request, pk):
        """
        This method is called when a POST request is made to the endpoint "patients/<int:pk>/update_diagnose/"
        The medical data of the patient with the given pk will be updated with the arguments of the POST request.

        Only Users of the group "Doctor" are allowed to make a request to this endpoint. The policy which is applied to
        POST requests to this endpoint is policy "Only Doctor can update patients diagnose"
        @param request: Request, which was made to the Server
        @param pk: id of the patient, whose medical data will be displayed
        """
        user_is_anonym = await sync_to_async(lambda: request.user.is_anonymous)()
        if user_is_anonym:
            return redirect('medical:index')
        form = UpdatePatientDiagnose(request.POST)

        if form.is_valid():
            await Patient.objects_patients.update_patient_medical_data(pk, **form.cleaned_data)
            return redirect('medical:patient', pk)

        messages.error(self.request, 'Form is invalid')
        return HttpResponseRedirect(self.request.path_info)


class PatientData(View):
    """
    Class based View to see and modify the medical data of a patient

    GET and POST requests are both pre_enforced with SAPL
    """

    @pre_enforce
    async def get(self, request, pk):
        """
        This method is called when a GET request is made to the endpoint "patients/<int:pk>/update_patient_data/"
        A page is rendered, which shows the general data of the patient with the given pk.

        Only Users of the group "Nurse" are allowed to make a request to this endpoint. The policy which is applied to
        GET requests to this endpoint is policy "Only Nurse can update patients general data"

djangoDemo/medical/templates/medical/patients/blood_pressure.html
{% extends 'medical/base.html' %}

{% block content %}
    <script>
        window.onload = function() {
            const socket = new WebSocket('ws://localhost:8000/ws/blood_pressure');

            socket.onopen = function(event) {
                console.log('WebSocket opened');
                socket.send('Hello, server!');
            };

            socket.onmessage = function(event) {
                const data = JSON.parse(event.data);
                const time = data.time;
                const bloodPressure1 = data.blood_pressure_1;
                const bloodPressure2 = data.blood_pressure_2;

                if (data.error) {
                    alert(data.error)
                }
                var pressurefield = document.getElementById("pressure");
                var timefield = document.getElementById("time");
                if ((bloodPressure1 > 100 && bloodPressure1 < 160) && (bloodPressure2 > 70 && bloodPressure2 < 95)){
                    pressurefield.style.color = "green";
                    pressurefield.style="font-size: 1REM; color: green";
                }
                else {
                    pressurefield.style.color = "red";
                    pressurefield.style="font-size: 3REM; color: red";
                }

                pressurefield.innerText = bloodPressure1+"/"+bloodPressure2;
                timefield.innerText = time;
            };
        };
    </script>
    <h3 class="mt-2">Blood pressure of {{ patient.name }}</h3>
    <hr class="mt-0 mb-4">
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ patient.name }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            {% if patient.id %}
                                <tr>
                                    <th>Patiend ID:</th>
                                    <td>{{ patient.id }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.icd11_code %}
                                <tr>
                                    <th>ICD11Code:</th>
                                    <td>{{ patient.icd11_code }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.diagnosis_text %}
                                <tr>
                                    <th>Diagnosis:</th>
                                    <td>{{ patient.diagnosis_text }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.attending_doctor %}
                                <tr>
                                    <th>Attending Doctor:</th>
                                    <td>{{ patient.attending_doctor }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.room_number %}
                                <tr>
                                    <th>Room:</th>
                                    <td>{{ patient.room_number }}</td>
                                </tr>
                            {% endif %}
                                <tr>
                                    <th>Current time:</th>
                                    <td id="time">unknown</td>
                                </tr>
                                <tr>
                                    <th>Blood pressure:</th>
                                    <td id="pressure">unknown</td>
                                </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

djangoDemo/medical/templates/medical/patients/detailview.html
{% extends 'medical/base.html' %}

{% block content %}

    <h3 class="mt-2">Patient: {{ patient.name }}</h3>
    <hr class="mt-0 mb-4">
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ patient.name }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            {% if patient.id %}
                                <tr>
                                    <th>Patiend ID:</th>
                                    <td>{{ patient.id }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.icd11_code %}
                                <tr>
                                    <th>ICD11Code:</th>
                                    <td>{{ patient.icd11_code }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.diagnosis_text %}
                                <tr>
                                    <th>Diagnosis:</th>
                                    <td>{{ patient.diagnosis_text }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.attending_doctor %}
                                <tr>
                                    <th>Attending Doctor:</th>
                                    <td>{{ patient.attending_doctor }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.room_number %}
                                <tr>
                                    <th>Room:</th>
                                    <td>{{ patient.room_number }}</td>
                                </tr>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="row" style="justify-content: space-around">
        <a class="waves-effect waves-light btn-large"
           href="{% url 'medical:update_patient' patient.id %}">Update this
            Patient</a>
        <a class="waves-effect waves-light btn-large"
            href="{% url 'medical:update_patient_diagnose' patient.id %}">Update
            Diagnose</a>
        <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="waves-effect waves-light btn-large" >DELETE</button>
    </form>
    </div>


    {#    <button type="submit" method="post">Delete</button>#}
    {#    <a href="{% url 'medical:patient' patient.id %}" class="btn btn-danger" method="post">Delete this Patient</a>#}


{% endblock %}

djangoDemo/medical/templates/medical/patients/new_patient.html
{% extends 'medical/base.html' %}

{% block content %}
    <form method="post">

        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Create" class="btn btn-primary" style="margin: auto;text-align: center; justify-content: center;justify-self: center;justify-items: center">
    </form>
{% endblock %}

djangoDemo/medical/templates/medical/patients/patient_list.html
{% extends 'medical/base.html' %}


{% block title %} - Patient List{% endblock %}

{% block content %}
    {#    {% enforce  action="'patientList.view'" resource="{ 'patients' : { 'id' : patient['id'], 'name' : patient['name'], 'medicalRecordNumber': patient.medicalRecordNumber, 'roomNumber': patient.roomNumber } }" %}#}

    <h3 style="text-align: center">Patient List</h3>


    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Patient List</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Room Nr.</th>
                                <th scope="col">Name</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for patient in patients %}
                                <tr>
                                    <td>{{ patient.id }}</td>
                                    <td>{{ patient.room_number }}</td>
                                    <td><a href="/patients/{{ patient.id }}">{{ patient.name }}</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <a class="waves-effect waves-light btn-large"
           style=" margin: auto;text-align: center" href="{% url 'medical:new_patient' %}">add new patient</a>
    </div>


{% endblock %}

djangoDemo/medical/templates/medical/patients/pulse.html
{% extends 'medical/base.html' %}

{% block content %}
    <script>
        window.onload = function() {
            const socket = new WebSocket('ws://localhost:8000/ws/pulse');
            const numberList = document.getElementById('number-list');

            socket.onopen = function(event) {
                console.log('WebSocket opened');
                socket.send('Hello, server!');
            };

            socket.onmessage = function(event) {
                const data = JSON.parse(event.data);
                const time = data.time;
                const pulse = data.pulse;

                if (data.error) {
                    alert(data.error)
                }
                var pulsefield = document.getElementById("pulse");
                var timefield = document.getElementById("time");
                if (pulse < 95 && pulse > 65){
                    pulsefield.style.color = "green";
                    pulsefield.style="font-size: 1REM; color: green";
                }
                else {
                    pulsefield.style.color = "red";
                    pulsefield.style="font-size: 3REM; color: red";
                }

                pulsefield.innerText = pulse;
                timefield.innerText = time;
            };
        };
    </script>
    <h3 class="mt-2">Pulse of {{ patient.name }}</h3>
    <hr class="mt-0 mb-4">
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ patient.name }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            {% if patient.id %}
                                <tr>
                                    <th>Patiend ID:</th>
                                    <td>{{ patient.id }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.icd11_code %}
                                <tr>
                                    <th>ICD11Code:</th>
                                    <td>{{ patient.icd11_code }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.diagnosis_text %}
                                <tr>
                                    <th>Diagnosis:</th>
                                    <td>{{ patient.diagnosis_text }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.attending_doctor %}
                                <tr>
                                    <th>Attending Doctor:</th>
                                    <td>{{ patient.attending_doctor }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.room_number %}
                                <tr>
                                    <th>Room:</th>
                                    <td>{{ patient.room_number }}</td>
                                </tr>
                            {% endif %}
                                <tr>
                                    <th>Current time:</th>
                                    <td id="time">unknown</td>
                                </tr>
                                <tr>
                                    <th>Pulse:</th>
                                    <td id="pulse">unknown</td>
                                </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

djangoDemo/medical/templates/medical/patients/update_diagnose.html
{% extends 'medical/base.html' %}

{% block content %}
    <h3 class="mt-2">Patient: {{ patient.name }}</h3>
    <hr class="mt-0 mb-4">
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ patient.name }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            {% if patient.room_number %}
                                <tr>
                                    <th>Room:</th>
                                    <td>{{ patient.room_number }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.icd11_code %}
                                <tr>
                                    <th>icd11 Code:</th>
                                    <td>{{ patient.icd11_code }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.diagnosis_text %}
                                <tr>
                                    <th>Diagnose:</th>
                                    <td>{{ patient.diagnosis_text }}</td>
                                </tr>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form method="post">

        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Update" class="btn btn-primary">
    </form>

{% endblock %}

djangoDemo/medical/templates/medical/patients/update_patient.html
{% extends 'medical/base.html' %}


{% block content %}
    <h3 class="mt-2">Patient: {{ patient.name }}</h3>
    <hr class="mt-0 mb-4">
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- DataTales Example -->

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ patient.name }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            {% if patient.room_number %}
                                <tr>
                                    <th>Room:</th>
                                    <td>{{ patient.room_number }}</td>
                                </tr>
                            {% endif %}
                            {% if patient.attending_doctor %}
                                <tr>
                                    <th>Attending Doctor:</th>
                                    <td>{{ patient.attending_doctor }}</td>
                                </tr>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form method="post">

        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Update" class="btn btn-primary">
    </form>

{% endblock %}